### PR TITLE
Add architecture doc

### PR DESCRIPTION
**Pull request by sbtaylor15**
Fixes ortelius/ortelius#559.

Please comment on this PR for changes needed to the doc.

### CODE REVIEW

**Comment by sbtaylor15** [comment]
Look at `docs/Ortelius XRPL Architecture and Design.md` in the PR

**Review by Arvind644 — APPROVED** [review]

**Review by codeWithUtkarsh — APPROVED** [review]
/lgtm

**Comment by TonyCarratoSSS** [comment]
Steve, some immediate thought on things I'd expect to see in an architecture document:
1) An overal logical diagram for the system, showing the logical components and how they are related
2) Either a logical flow or, even better, an interaction diagram
3) Non-functional requirements
4) A record of major architectural decisions
5) Architecturally significant use case

**Review by josephakayesi — APPROVED** [review]
/lgtm

**Comment by sbtaylor15** [comment]
@TonyCarratoSSS @Arvind644 @codeWithUtkarsh @josephakayesi @sachajw - Please re-review.  Tried to address the items that Tony pointed out.   Let me know if the updates make sense.

**Review by josephakayesi — APPROVED** [review]
Love the detailing. \lgtm

**Review by Arvind644 — APPROVED** [review]

**Comment by TonyCarratoSSS** [comment]
Looks good, Steve.   With regard to the non-functional requirements, do you want 5o say anything about expectations for:- performance - availability/uptime- security----Tony ***@***.***   +1-505-850-5524On Mar 8, 2023, at 3:32 PM, Steve Taylor ***@***.***> wrote:﻿
@TonyCarratoSSS @Arvind644 @codeWithUtkarsh @josephakayesi @sachajw - Please re-review.  Tried to address the items that Tony pointed out.   Let me know if the updates make sense.

**Comment by TonyCarratoSSS** [comment]
@sbtaylor15  - Looked for something on non-functional issues, as I mentioned in my email, covering expected uptime, performance and scalability but don't find such.  Can you point me to where you converted those, please.

**Pull request merged**
